version: '3.8'

# Override compose to run the single "all-in-one" master image instead of
# the separate `php-fpm` service. Note: nginx is run as a separate service/image
# and is not bundled into the all-in-one image. Use together with docker-compose.full.yml:
#
# IMAGE_TAG=dev docker compose -f docker-compose.full.yml -f docker-compose.allinone.yml up -d

services:
  # Replace the php-fpm service with the single all-in-one m3u-editor image
  m3u-editor:
    build:
      context: .
      dockerfile: Dockerfile
      target: allinone
      args:
        GIT_BRANCH: ${GIT_BRANCH:-local}
        GIT_COMMIT: ${GIT_COMMIT:-local}
        GIT_TAG: ${GIT_TAG:-local}
    image: sparkison/m3u-editor:${IMAGE_TAG:-latest}
    environment:
      - APP_ENV=${APP_ENV:-local}
      - APP_DEBUG=${APP_DEBUG:-true}
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=${PG_PORT:-5432}
      - DB_DATABASE=${PG_DATABASE:-m3ue}
      - DB_USERNAME=${PG_USER:-m3ue}
      - DB_PASSWORD=${PG_PASSWORD:-m3ue}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - APP_PORT=${APP_PORT:-36400}
      - REVERB_PORT=${REVERB_PORT:-36800}
      - M3U_PROXY_PORT=${M3U_PROXY_PORT:-38085}
      - M3U_PROXY_ENABLED=true
      - M3U_PROXY_URL=${M3U_PROXY_URL:-http://m3u-proxy:8085}
    volumes:
      - ./docker-config:/var/www/config
      - ./:/var/www/html:cached
    depends_on:
      - postgres
      - redis
      - m3u-proxy
    ports:
      - '${APP_PORT:-36400}:${APP_PORT:-36400}'
      - '${REVERB_PORT:-36800}:${REVERB_PORT:-36800}'
      - '${M3U_PROXY_PORT:-38085}:${M3U_PROXY_PORT:-38085}'
