# Base compose file used to build the images that get pushed to Docker Hub.
# Use this in CI to build and tag images (dev/experimental/latest).
# This file always uses `build:` so it produces images that can be pushed.

services:
  # Nginx image (nginx stage)
  m3u-editor-nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: nginx
      args:
        GIT_BRANCH: ${GIT_BRANCH:-local}
        GIT_COMMIT: ${GIT_COMMIT:-local}
        GIT_TAG: ${GIT_TAG:-local}
    image: sparkison/m3u-editor-nginx

  # Postgres image (postgres stage)
  m3u-editor-postgres:
    build:
      context: .
      dockerfile: Dockerfile
      target: postgres
      args:
        GIT_BRANCH: ${GIT_BRANCH:-local}
        GIT_COMMIT: ${GIT_COMMIT:-local}
        GIT_TAG: ${GIT_TAG:-local}
    image: sparkison/m3u-editor-postgres

  # Redis image (redis stage)
  m3u-editor-redis:
    build:
      context: .
      dockerfile: Dockerfile
      target: redis
      args:
        GIT_BRANCH: ${GIT_BRANCH:-local}
        GIT_COMMIT: ${GIT_COMMIT:-local}
        GIT_TAG: ${GIT_TAG:-local}
    image: sparkison/m3u-editor-redis

  # PHP-FPM runtime image (runtime stage)
  m3u-editor-fpm:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
      args:
        GIT_BRANCH: ${GIT_BRANCH:-local}
        GIT_COMMIT: ${GIT_COMMIT:-local}
        GIT_TAG: ${GIT_TAG:-local}
    image: sparkison/m3u-editor-fpm

# NOTE: This file is intended for building images only. The resulting images
# are pushed to Docker Hub and then consumed by docker-compose.full.yml or
# by users' custom compose files which pull pre-built images.
